### ISSUE TITLE
Distance to restroom incorrect

### ISSUE THREAD

**Issue by daniellee0** [dajuniors/phase5#1]
Minor Issue. When calculating the distance to a restroom displayed on the right, the actual distance is several miles off. For example, OneRestroomAway says that the distance from my location to Padelford Hall is 9.43 miles. However, after replicating this on Google Maps and constructing the exact same route, the actual distance is ~14 miles. To replicate:

1. Click on a restroom located on map or sidebar
2. Reconstruct exact route on Google Maps
3. Compare distances provided by both OneRestroomAway and Google Maps.

**Comment by kathlu** [comment]
The reason why the distance if off between the distance on Google Maps and the one we provided on OneRestroom Away is due to the way we calculated the distance. We calculated the exact distance between the two coordinates. Whereas, Google Maps will display the distance based on route, hence, the route may have a longer distance. It is rather a design decision that we made. We may choose to change it in future releases.

(Example picture of the difference between distance (not our picture))
![62338837_2294344863985704_8759921731059056640_n](https://user-images.githubusercontent.com/26660940/59237943-f2788380-8bb0-11e9-80de-2f2d1290c66f.png)
