### ISSUE TITLE
When I click a different location from my own and go to a different tab and come back it automatically snaps back to current location

### ISSUE THREAD

**Issue by aliar97** [dajuniors/phase5#15]
This is a major issue, theres no way for me to get to my current location other than just going to one tab and then coming this apps's tab. When I wanna look at a particular place for its restrooms and switch tabs for a second I lose where I was at. There should just be a got to current location button in the key. To reproduce this bug, try launching the app first. It will then go to your location. Then click a faraway location then click on a different tab in your browser than come back to the app's tab and it will just snap back to current location.

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/issues/7
https://github.com/dajuniors/phase5/commit/40486c08b6e03fdfa6ae314251b4c4ae768f3657
Duplicate issue, issue resolved but need to merge changes to gh-pages branch.

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/commit/40486c08b6e03fdfa6ae314251b4c4ae768f3657
This issue has been fixed. The map should not zoom back to the location every time the user goes away and back to the website. Although, we believe this is not a major issue. It is a minor issue simply because the user has to move the map themselves to find their current location. The functionality is still there, it just requires some more steps. We have added a go to current location button as well.
