### ISSUE TITLE
Not mobile friendly

### ISSUE THREAD

**Issue by VanelyRuiz** [dajuniors/phase5#16]
![IMG_1FAC8664346D-1](https://user-images.githubusercontent.com/35097969/59249473-b9a0d480-8bd9-11e9-83dd-6604230f609b.jpeg)

Your app is difficult to use on mobile because it's not responsive. Some of the text is too large and many parts are unreadable because they're cut off. This type of application would most likely be used on mobile because people look for restrooms when they're on the go and not home. It's not very practical to pull out your laptop and look for wifi when you need to use the restroom.

**Comment by dayoungcheong** [comment]
Although we understand that our application is not yet mobile friendly, we have decided not to fix this for our next release as we do not have the time. A considerable amount of time went into trying to make our app mobile friendly, and every time one thing would be fixed, another bug would pop up. Also, because of how we initially structured our HTML, it would be difficult to get it looking exactly the way we want on mobile. We have decided not to fix this as it was a low-level priority and did not have the time to properly implement this without getting new bugs.
