### ISSUE TITLE
Cannot find location

### ISSUE THREAD

**Issue by jacklchang** [dajuniors/phase5#19]
I tried inputting multiple valid address and it was not able to locate it. 
For example, clicking on Allen Library Floor G-3
Get Directions 
Address: 400 Broad St

**Comment by kathlu** [comment]
https://github.com/dajuniors/phase5/commit/b076077b1fd87385674996c9109e8f3976bf8999
https://github.com/dajuniors/phase5/commit/bc160ccb9ba5d83bb3f2a4888fec03a2ee20195a
https://github.com/dajuniors/phase5/commit/e934171fb6e250a9b7690e1654411f94ab6f5776

There are a few reasons why this bug appeared. The user inputed 400 Broad St, this is not a full address. We updated the box to say "Enter Full Starting Address" to clarify for the user that they must enter in the full address and not just the street name. Since the user only inputed 400 Broad St, the first result given by Mapbox was to the same address of 400 Broad St, but in Canada. This request went through our search and did not render any directions. Mapbox limits the distance between two points for directions. We added an error message to inform the user.
