### ISSUE TITLE
Direction does not match to map

### ISSUE THREAD

**Issue by yiranni** [dajuniors/phase5#26]
Some of the direction instructions do not match the direction on the map (example provided below). It seems like you need to head north, turn left, go straight, and turn right on the map. But the instruction tells me to make two left turns. 
![image](https://user-images.githubusercontent.com/32496771/59305705-a29cc980-8c4f-11e9-806a-e4ff6f7b065f.png)
![image](https://user-images.githubusercontent.com/32496771/59305747-b6e0c680-8c4f-11e9-96cb-fe8693e4039f.png)

**Comment by kathlu** [comment]
This is an issue that is related to the Mapbox Navigation API. The API call to receive this information provides us with both the coordinates to render the entire route and the directions steps. The discrepancy between the route line and the directions are due to the API. Therefore, we are not able to fix this issue.
