### ISSUE TITLE
Icons are blurry on high DPI devices, making them hard to interpret

### ISSUE THREAD

**Issue by vincentmvdm** [dajuniors/phase5#29]
The app's icons are blurry on retina devices, such as MacBook Pros and many other modern phones and laptops. This is a UX problem because the app relies heavily on them and users need to be able to interpret them at all times.

Steps to reproduce:

1. Go to the app on a @2X+ device, such as a MacBook Pro with a retina display

Steps to resolve:

- Upload multiple PNG versions of your icon using the srcset property (https://www.w3schools.com/tags/att_source_srcset.asp)
- Avoid potentially blurry images all together by using SVGs instead of PNGs

**Comment by dayoungcheong** [comment]
We looked at our app through 2 MacBook Pros with retina and could not reproduce this error. Naveen and Katherine both report the icons looking fine/the same on their laptops (Macbook Pros). Because of this, and because we do not count this as an actual bug, we will not be changing this by the next release.
