### ISSUE TITLE
Location Services Popup is inconsistent across browsers.

### ISSUE THREAD

**Issue by MatthewSVogt** [dajuniors/phase5#3]
Using MS Edge, the user is required to go into their windows settings to allow location services.
Firefox developer edition is more similar to chrome, but has different wording.

**Comment by kathlu** [comment]
`impossible` This is something that we cannot fix as it is specific to the browser. We call the API to request user for the user's current location. If it does not prompt the user, this may be due to the settings in the browser or user permissions. We have no way of passing these restrictions to force prompt the user. As for the different wording, we cannot make this consistent. The location prompt is restricted from changes to prevent malicious developers from tricking users. 

https://stackoverflow.com/questions/11787376/custom-html5-geolocation-prompt
https://stackoverflow.com/questions/27014154/how-do-i-reset-the-geo-location-service-settings-each-time-my-page-loads-with-ht
https://stackoverflow.com/questions/8054005/how-to-make-google-maps-to-request-again-for-location-permissions
